### ISSUE TITLE
How can I import both Seurat assay(integrated and RNA) to monocle and do further pseudotime trajectory?

### ISSUE THREAD

**Issue by Sophia409** [cole-trapnell-lab/monocle3#111]
Hi,cole-trapnelllab:
thank you for your work!
Recently monocle v2 has been deprecated and v3 has been finalized. I can manually use the seurat intergrated data for constructing a pseudotime trajectory in monocle.But now we can only import one assay(integrated or RNA) to monocle and do further pseudotime trajectory.So I'm wondering if your added support for the  seurat v3 mutiple assay object.
For example,I have integrated data from mouse cells from different times,including E11,15,18,p5,p10,p30. And I want to do further linage tracing and pseudotime trajectory.My data was batch corrected,so it's not right for me to just use one assay to do analysis.**Because if I import the integrated assay to monocle for clustering,monocle will automatically find markers for these cluster referring to integrated data matrix.**[[And in fact, Seurat said that for data integration these values should not be interpreted next, and  contain negative values as seurat are subtracting values from datasets to remove technical differences.] ](https://github.com/satijalab/seurat/issues/1057#issuecomment-454145423)
But **if import the RNA assay to monocle for clustering,the data matrix was not batch corrected**,it still not right to use it for do clustering and pseuodotime analysis.
I'm really confused and waiting for your advise.Thank you!
(https://github.com/satijalab/seurat/issues/1057#issuecomment-454145423)
@ctrapnell

**Comment by dwucsf** [comment]
@Sophia409, I'm getting good batch correction with Monocle 3.0.1.0. I'm planning to use the batch correction method internal to Monocle to load into my pseudotime analysis

**Comment by Sophia409** [comment]
Hi,
Do you compare the batch corrected result between seurat and monocle? In my experiment, seurat is much better than monocle.The first picture is done by monocle,and the second one is done by seurat. So,I really doubt the monocle corrected result .And maybe I can try the Scanpy.
| |
yuhong
|
|
yuhongruoyi@163.com
|
签名由网易邮箱大师定制
On 6/19/2019 13:31，dwucsf<notifications@github.com> wrote：

@Sophia409, I'm getting good batch correction with Monocle 3.0.1.0. I'm planning to use the batch correction method internal to Monocle to load into my pseudotime analysis

**Comment by ctrapnell** [comment]
Importing adjusted or pre-normalized expression values into cell_data_set objects is not a good idea, because such matrices are often dense, and could exhaust the memory of the computer. Allowing users to import their values from Seurat's corrections directly is pretty tricky. We aren't sure about the best way to support this right now, and so I am going to close this issue for now. 

However, we do appreciate the need for nonlinear batch correction and dataset alignment. We plan to implement this soon (e.g. see #105). Specifically, we plan to add an option to preprocess_cds() to allow users to align cells from different batches using mutual-nearest-neighbor type methods (e.g. mnnCorrect).

**Comment by dwucsf** [comment]
Thank you very much for your explanation, @ctrapnell!

**Comment by Sophia409** [comment]
@ctrapnell @hpliner Hello, when will you finish adding mnnCorrect method to preprocess_cds() to allow users to align cells from different batches?
