### ISSUE TITLE
Forcing trajectory connections

### ISSUE THREAD

**Issue by dwucsf** [cole-trapnell-lab/monocle3#132]
I have two populations (see attached plot; partitions 1 and 2 are the populations I'm referring to) that I know are derived from the same progenitor pool. However, there is no trajectory that connects them. Is there a way to force trajectories (or partitions) to connect?
[Monocle-Partitions.pdf](https://github.com/cole-trapnell-lab/monocle3/files/3318526/Monocle-Partitions.pdf)

**Comment by hpliner** [comment]
Thank you for using Monocle 3. 

This report appears to be a question rather than a bug or feature request. Please post your question to the Monocle 3 user group here: https://groups.google.com/forum/#!forum/monocle-3-users so that we and the community can address it! If you believe this is a bug/feature request and was closed in error, please reopen.

- Monocle 3 developers

**Comment by pangwopi** [comment]
If you set use_partition = FALSE when calling learn_graph, that should force a connected trajectory for the whole dataset.
