### ISSUE TITLE
Pruning branches 

### ISSUE THREAD

**Issue by dwucsf** [cole-trapnell-lab/monocle3#134]
Is there a way to prune branches in monocle3? My trajectory has a lot of mini-branches that come off the main branch (see attached plot).

[Pseudotime.pdf](https://github.com/cole-trapnell-lab/monocle3/files/3318625/Pseudotime.pdf)

**Comment by hpliner** [comment]
Thank you for using Monocle 3. 

This report appears to be a question rather than a bug or feature request. Please post your question to the Monocle 3 user group here: https://groups.google.com/forum/#!forum/monocle-3-users so that we and the community can address it! If you believe this is a bug/feature request and was closed in error, please reopen.

- Monocle 3 developers
