### ISSUE TITLE
Can I use time metadata in trajectory?

### ISSUE THREAD

**Issue by jogiles** [cole-trapnell-lab/monocle3#137]
Hello!

Is it possible to include time point metadata in the trajectory analysis? I have 4 time points: day 0, 8, 15, 30. There are no cells in day 0 and day 8 that are connected.

Thank you!
Josephine

**Comment by hpliner** [comment]
Thank you for using Monocle 3. 

This report appears to be a question rather than a bug or feature request. Please post your question to the Monocle 3 user group here: https://groups.google.com/forum/#!forum/monocle-3-users so that we and the community can address it! If you believe this is a bug/feature request and was closed in error, please reopen.

- Monocle 3 developers

**Comment by hpliner** [comment]
Updated link https://groups.google.com/d/forum/monocle-3-users
