### ISSUE TITLE
Custom color palette for plot_cells_3d

### ISSUE THREAD

**Issue by lambdamoses** [cole-trapnell-lab/monocle3#163]
It seems that `plot_cells_3d` doesn't give an option for custom color palettes. For `plot_cells`, I can use custom palettes with `scale_color_*`, but I can't do that kind of thing for `plotly`. Can you add an argument in `plot_cell_3d` for custom palettes?

**Comment by hpliner** [comment]
This is now fixed in develop, I added two options, color_palette for passing a list of categorical colors (i.e. color_palette = c("green", "red", "blue")), and color_scale for passing a plotly colorscale for coloring numeric values (i.e. color_scale = "Earth"). I found a list of possible scales here: https://community.plot.ly/t/what-colorscales-are-available-in-plotly-and-which-are-the-default/2079

This will be released as 0.2.0!
