### ISSUE TITLE
Can I change the color in function `plot_cell()`?

### ISSUE THREAD

**Issue by pengpengyang94** [cole-trapnell-lab/monocle3#181]
I want to change the default color in function `plot_cell()` , how should I set it? 3q

**Comment by hpliner** [comment]
Thank you for using Monocle 3. 

This report appears to be a question rather than a bug or feature request. Please post your question to the Monocle 3 user group here: https://groups.google.com/d/forum/monocle-3-users so that we and the community can address it! If you believe this is a bug/feature request and was closed in error, please reopen.

- Monocle 3 developers

plot_cells outputs a ggplot object which can then be recolored using ggplots functionality. For example plot_cells(cds, color_cells_by = "culture_plate") + scale_color_manual(values = c("red", "blue"))

**Comment by pengpengyang94** [comment]
Thank you very much for your detailed reply. This gives me a deeper understanding of the drawing, and I will put the question and your reply on Monocle 3 user group.
