### ISSUE TITLE
How to plot the genes branched heatmap in monocle3?

### ISSUE THREAD

**Issue by AIBio** [cole-trapnell-lab/monocle3#182]
Hi, recently I have met a problem with using monocle3 to analyze scRNAseq dataset.
I cannot plot the genes branched heatmap in monocle3. But the monocle2 do support this function.
Did monocle3 deprecat it?

**Comment by hpliner** [comment]
Branched heatmaps are no longer supported in Monocle3 because trajectories are generally more complex than just 2 branches. This functionality has been replaced with plotting gene modules, which is demonstrated here: https://cole-trapnell-lab.github.io/monocle3/monocle3_docs/#finding-modules-of-co-regulated-genes
