### ISSUE TITLE
Semi-supervised pseudoalignment

### ISSUE THREAD

**Issue by Acribbs** [cole-trapnell-lab/monocle3#225]
Im really enjoying playing around with monocle3 and have a quick, and probably naive question.

Given that pseudoalignment is marked by the roots of the trajectory, which are defined by identifying spots on a UMAP. I wondered if there is still a way of performing semi-supervised pseudotime by supplying a set of genes that define a biological process like in the original monocle?

**Comment by ctrapnell** [comment]
Glad you're enjoying Monocle3. You can perform semi-supervised dimensionality reduction by passing a list of gene ids to `preprocess_cds()` through the `use_genes` argument. They should then constrain the subsequent alignment with `align_cds()`.

In the future please send questions to the google group rather than submitting them as issues. You can post to the group here: 

https://groups.google.com/forum/#!forum/monocle-3-users
