### ISSUE TITLE
How does fit_models() works on categorical terms?

### ISSUE THREAD

**Issue by gundalav** [cole-trapnell-lab/monocle3#237]
Hi, 

I am referring to Monocle3's [regression based differential expression analysis](https://cole-trapnell-lab.github.io/monocle3/docs/differential/#regression-analysis).

In the example the model formula`~embryo.time`  is numerical value:

`gene_fits <- fit_models(cds_subset, model_formula_str = "~embryo.time")`

As stated in the tutorial the formula is 

![x](https://user-images.githubusercontent.com/8143832/66987310-83c9aa80-f0fb-11e9-8194-eb5515dcf2a3.jpg)

It is understood that `~embryo.time` is related to `x_t`. 
However how does the regression is formulated when model formula is of categorical type ( e.g. 
treatment1, treatment2, etc) ?

Hope to hear from you again. 
G.V.

**Comment by hpliner** [comment]
Thank you for using Monocle 3. 

This report appears to be a question rather than a bug or feature request. Please post your question to the Monocle 3 user group here: https://groups.google.com/d/forum/monocle-3-users so that we and the community can address it! If you believe this is a bug/feature request and was closed in error, please reopen.

- Monocle 3 developers

**Comment by olaf-c** [comment]
Given the current state of the google group, could this question be reopened here?
