### ISSUE TITLE
Use custom dimension reduction for learn_graph

### ISSUE THREAD

**Issue by lambdamoses** [cole-trapnell-lab/monocle3#241]
It seems that the current version of `monocle3` forces us to use UMAP to infer the trajectory: https://github.com/cole-trapnell-lab/monocle3/blob/9becd94f60930c2a9b51770e3818c194dd8201eb/R/learn_graph.R#L69

However, I'm a bit skeptical about whether this is the best approach. The actual latent dimensionality of the data is most likely to be much greater than 2 or 3 used in UMAP, so it won't be surprising that using 2 or 3 dimensions in UMAP will cause significant distortions in the data. Also see this preprint that characterized such distortion in common non-linear dimension reduction techniques: http://dx.doi.org/10.1101/689851 

So it would be nice for users to use custom dimension reductions for trajectory inference, such as a larger number of principal components, for a trade off between distortion and removing noise. Though the trajectory in a higher dimension can't be visualized directly (though we can still project the vertices into 2 dimensions and connect them), it would be better if it better represents distances between cells.

**Comment by Connorr0** [comment]
I would like to piggyback off this comment with another question/point. I have been having similar feelings and have noticed a number of situations where simply the difference between two and three dimensions of UMAP can create stark changes in interpretation. In particular, I have seen groups that are discontinuous in two dimensions be joined in three dimensions.

Also while this is limited to UMAP usage you can set the reduce dimensions function to return more than three dimensions.

**Comment by alex-wenzel** [comment]
I would also like to piggyback on this issue, as I am trying to perform a pseudotime analysis with the results of `align_cds()` but it doesn't appear possible at the moment due to this same hardcoding issue. When I try to run `learn_graph()` after running clustering with `reduction_method = "Aligned"`, I get `Error: No cell clusters for UMAP calculated. Please run cluster_cells with reduction_method = UMAP before running learn_graph.`

**Comment by brgew** [comment]
Hi,

The Monocle3 developers chose to require UMAP dimension reduction for learn_graph() because they believe that it is the best method available for this purpose. Other methods have more substantial shortcomings, for example, t-SNE tends to represent local distances with some accuracy but not global distances, in contrast to UMAP, which can better represent global distances. You can change the number of embedded dimensions in UMAP reductions using the n_components parameter if you believe that the reduction to two dimensions introduces unacceptably severe distortions. (Add n_components to the reduce_dimension() call and it will be passed to umap.)
 
You can learn more about the UMAP parameters available in Monocle3 using the R command

`?uwot::umap`

or go to the [UWOT www site](https://cran.r-project.org/web/packages/uwot/index.html).

**Comment by ctrapnell** [comment]
Just to clarify before closing, learn_graph() is not to two or even three dimensions. As @brgew said above, you can increase the dimensionality of your UMAP plots to higher than three if you want to learn a "hypertrajectory". As for other types of dimensionality reduction, we restrict to UMAP mainly to keep people from trying to learn trajectories in t-SNE plots, which we feel is generally frought and bad practice.

**Comment by yanwengong** [comment]
Is there a way to import an existing UMAP into monocle3, and show trajectory on top of it? In addition, when using monocle3 to generate UMAP, can we specify number of genes used in the PCA, and number of PCs used to generate UMAP?

**Comment by tanpuekai** [comment]
> I would also like to piggyback on this issue, as I am trying to perform a pseudotime analysis with the results of `align_cds()` but it doesn't appear possible at the moment due to this same hardcoding issue. When I try to run `learn_graph()` after running clustering with `reduction_method = "Aligned"`, I get `Error: No cell clusters for UMAP calculated. Please run cluster_cells with reduction_method = UMAP before running learn_graph.`
> 
> **EDIT**: If anyone finds this thread and has the same issue, a quick work-around is to just move the contents of the `Aligned` slot to the `UMAP` slot
> 
> ```r
> cds@int_colData@listData$reducedDims@listData$UMAP <- cds@int_colData@listData$reducedDims$Aligned
> ```

great. save a lot of time for us.  thank you.
