### ISSUE TITLE
Use tSNE cell.embeddings instead of UMAP for cluster_cells() and learn_graph()

### ISSUE THREAD

**Issue by ChevyXu** [cole-trapnell-lab/monocle3#242]
Hi developers,

Since tSNE reduction is not supported by learn_graph() function, is there a possibility to do learn_graph() using the tSNE reduction by setting the cds@reducedDims$UMAP value with the tSNE cell.embeddings?

I've tried and got a fair result, while not known whether ii is acceptable use.

Thanks for your reply.

**Comment by panxiaoguang** [comment]
I also want to know how to use "TSNE" to calculate it.

**Comment by brgew** [comment]
Hi,

The Monocle3 developers chose to require UMAP dimension reduction for learn_graph() because they believe that it is the best method available for this purpose. Other methods have more substantial shortcomings, for example, t-SNE tends to represent local distances with some accuracy but not global distances, in contrast to UMAP, which can better represent global distances. You can change the number of embedded dimensions in UMAP reductions using the n_components parameter if you believe that the reduction to two dimensions introduces unacceptably severe distortions. (Add n_components to the reduce_dimension() call and it will be passed to umap.)

You can learn more about the UMAP parameters available in Monocle3 using the R command

`?uwot::umap`

or go to the [UWOT www site](https://cran.r-project.org/web/packages/uwot/index.html).

**Comment by sarahhp** [comment]
Could you update the learn_graph documentation to mention that tSNE isn't supported?  In version 1.3.7 of monocle3 the description mentions both reductions.  And running with without cluster_cells called on the UMAP reduction (aka on the tSNE reduction instead) gives an uninformative error: 

![image](https://github.com/user-attachments/assets/6cf3e55f-4ae3-408b-9996-688aa1de0862)
