### ISSUE TITLE
Error with dim analysis Monocle3

### ISSUE THREAD

**Issue by aelias1** [cole-trapnell-lab/monocle3#305]
I use the code below immediately following my loading in data - which is shown in your documentation:

_cds <- preprocess_cds(_cds, num_dim = 100)
_cds <- reduce_dimension(_cds)
plot_cells(_cds)

I receive the error:
No trajectory to plot. Has learn_graph() been called yet?
cluster not found in colData(cds), cells will not be colored
cluster_cells() has not been called yet, can't color cells by cluster

I cannot find in your Monocle 3 documentation these commands...at least to use before the commands stated above.  I am using in data loaded from 10x

**Comment by hpliner** [comment]
This is not an error, it's just a message telling you that plot_cells won't be able to plot a trajectory because you haven't called learn_graph yet or color by cluster because you haven't done any clustering. You can set `show_trajectory_graph = FALSE` and set `color_cells_by` to something other than 'cluster' and then you won't get that message.
