### ISSUE TITLE
Multiple geneomes found; please specify one

### ISSUE THREAD

**Issue by polespin** [cole-trapnell-lab/monocle3#311]
Hello

When i tried to process my 10x single cell seqeuncing data with monocle3, there is a critical problem.

In first step, 

cds <- load_cellranger_data(pipestance_path =  "C:/HN00121833_10X_result/My _sample/filtered_feature_bc_matrix")
Error in get_genome_in_matrix_path(matrix_dir, genome) : 
  Multiple genomes found; please specify one. 
 Genomes present: barcodes.tsv.gz, features.tsv.gz, matrix.mtx.gz

What can i do for solving this problem?

**Comment by brgew** [comment]
Hi,

Comparing the error message with the R code for the load_cellranger_data() function, it appears to me that this function determines that you have a CellRanger version 2 data set because it cannot find, evidently, the subdirectory 'filtered_feature_bc_matrix'. That's odd because the function found the files in the filtered_feature_bc_matrix directory!

You are using a Windows machine, I am guessing. I wonder what happens if you try the command

cds <- load_cellranger_data(pipestance_path =
"C:\HN00121833_10X_result\My_sample\filtered_feature_bc_matrix")

That is, replace '/' with '\'.

If that fails and you are willing to try the 'develop' branch of monocle3, the function load_mm_data()
should work for you, I hope. That function call would be

cds <- load_mm_data(mat_path='C:\HN00121833_10X_result\My_sample\filtered_feature_bc_matrix\matrix.mtx.gz',
feature_anno_path='C:\HN00121833_10X_result\My_sample\filtered_feature_bc_matrix\features.tsv.gz',
cell_anno_path='C:\HN00121833_10X_result\My_sample\filtered_feature_bc_matrix\barcodes.tsv.gz',
feature_metadata_column_names=c('gene_short_name','type'))

(I guess that there are three columns of values in 'features.tsv.gz' and I am calling the third column 'type'...I don't know what it might be called.)

**Comment by hpliner** [comment]
Looks like this is solve, reopen if still an issue
