### ISSUE TITLE
monocle3 wont install on mac

### ISSUE THREAD

**Issue by bromleyjd** [cole-trapnell-lab/monocle3#418]
pkgbuild::check_build_tools(debug = TRUE)
Error: Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

I've tried installing gcc etc and reinstalling R several times, however, I still get the error above. How can I resolve this installation error on a mac? I have tried referencing past tickets here but they have not been able to fix this issue for me.

**Comment by brgew** [comment]
Hi,
What happens when you 'Call pkgbuild::check_build_tools(debug = TRUE) to diagnose the problem.'? There is information about pkgbuild at https://cran.r-project.org/web/packages/pkgbuild/readme/README.html.
When you open a terminal window and type 'gcc', what is returned?
Do you have Anaconda installed? If so this may interfere with building...in which case I wonder if you can remove Anaconda from your PATH variable and try again to install monocle3.

**Comment by brgew** [comment]
No response.
