### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by osmansharifi** [cole-trapnell-lab/monocle3#631]
I am trying to install monocle3 in R 4.2.1 in macOS Monterey.

I tried 
`BiocManager::install("monocle3")`
 I got the following error message :
Warning message:
package ‘monocle3’ is not available for Bioconductor version '3.15'

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

and it does not install

**Comment by florian-bach** [comment]
disclaimer: i'm not a dev on monocle3. but what your command does is ask to install monocle3 from bioconductor and it's not on there. on their website it says to run

```
install.packages("devtools")
devtools::install_github('cole-trapnell-lab/monocle3')
```
just in case this still doesn't work:
i also couldn't install monocle3. this appears to be because of the Matrix.utils dependency, but Matrix.utils was recently dropped from CRAN. I downloaded an archived version of matrix.utils and installed it from source and that fixed the issue for me and monocle3 installed correctly.
